version: '3.8'

services:
  customer_service:
    container_name: customer_service
    build: ./customer_service
    environment:
      - POSTGRES_USER=muhammadumar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=customerdb
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POST_SERVICE_PORT=9090
      - POST_SERVICE_HOST=post_service
      - LOG_LEVEL=develop
      - ENVIRONMENT=develop
    ports:
      - "9000:9000"
      


  post_service:
    container_name: post_service
    build: ./post_service
    environment:
      - POSTGRES_USER=muhammadumar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postdb
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - CUSTOMER_SERVICE_PORT=9000
      - CUSTOMER_SERVICE_HOST=customer_service
      - REVIEW_SERVICE_PORT=9900
      - REVIEW_SERVICE_HOST=review_service
      - LOG_LEVEL=develop
      - ENVIRONMENT=develop
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    links: 
      - customer_service
    ports:
      - "9090:9090"
  
  review_service:
    container_name: review_service
    build: ./review_service
    environment:
      - POSTGRES_USER=muhammadumar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=reviewdb
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POST_SERVICE_PORT=9090
      - POST_SERVICE_HOST=post_service
      - CUSTOMER_SERVICE_PORT=9000
      - CUSTOMER_SERVICE_HOST=customer_service
      - LOG_LEVEL=develop
      - ENVIRONMENT=develop
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    links:
      - post_service
    ports:
      - "9900:9900"

  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    environment:
      - POSTGRES_USER=muhammadumar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=customerdb
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
    links:
      - redis
      - customer_service
      - post_service
      - review_service
    ports:
      - "8800:8800"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6380:6379"      